### ISSUE TITLE
Add Treasury Implementation

### ISSUE THREAD

**Issue by lokka30** [Avankziar/AdvanceEconomyPlus#3]
A bunch of AdvanceEconomyPlus's features can be hooked natively through [Treasury](https://www.spigotmc.org/resources/treasury.99531/), from multiple accounts to multiple currencies :) I recommend checking out the library to see if you would like to use it in your project as an additional hook to Vault (as Vault does not have these features).

I'm the author of the library – we're currently working on an API revamp (version 2), so we recommend plugins to delay in writing an implementation for Treasury until we can release a beta version of v2.

**Comment by Avankziar** [comment]
Hello, so I know Treasury, because I had the same idea for a long time (and at the same time) and also implemented it as [InterfaceHub](https://github.com/Avankziar/InterfaceHub/wiki/ENG-Home) ([Comparison](https://github.com/Avankziar/InterfaceHub/wiki/ENG-Comparison) ;) ). And sry, the wiki for AEP have i updated today. (I am really slow..)
Personally, I myself do not know why I now again make the work to include Treasury, if everything IFH can also do ;).
But I think about it.

Avan

**Comment by lokka30** [comment]
The purpose of Treasury in this case is that other plugins – be it a jobs plugin, shops plugin, and what-not – are able to *utilise* these cool features without having to add a hook directly into each economy provider. It's the same reason you use Vault: so plugins can speak the same language when working with the server's economy.

**Comment by Avankziar** [comment]
"It's the same reason you use Vault", well I use Vault, but only secondary. Primary I use IFH, and this can "are able to utilise these cool features without having to add a hook directly into each economy provider" that too...

**Comment by lokka30** [comment]
The more the merrier, I think. If you're not interested, feel free to close the issue. :)
